### ISSUE TITLE
Fix contracts inheritance 

### ISSUE THREAD

**Issue by kinspotting** [api3dao/api3-dao#150]
Currently the inheritance structure of Api3Pool contract is implemented as a chain of 9 contracts being inherited on from another, what could be visualized as follows:

```
(Api3Pool)<==(TimeLockUtils)<==(ClaimUtils)<==(StakeUtils)<==(TransferUtils)<== (DelegationUtils)<==(RewardUtils)<==(GetterUtils)<==(StateUtils)
```

It might improve the readability and potential problems to change the contracts architecture and limit the inheritance chain to maximum 3 contracts.

**Comment by bbenligiray** [comment]
Let me fix the unit tests before this, should be done today

**Comment by aspiers** [comment]
I'm starting to look at this. The tests already pass for me though; curious what needs to be fixed?

**Comment by kinspotting** [comment]
> I'm starting to look at this. The tests already pass for me though; curious what needs to be fixed?

The idea is to shorten the inheritance chain and reduce the number of contracts

**Comment by aspiers** [comment]
[**@kinspotting**](https://github.com/kinspotting) commented on [April 2, 2021 8:15 AM](https://github.com/api3dao/api3-dao/issues/150#issuecomment-812372036 "2021-04-02T07:15:31Z - Replied by Github Reply Comments"):
> > I'm starting to look at this. The tests already pass for me though; curious what needs to be fixed?
> 
> The idea is to shorten the inheritance chain and reduce the number of contracts

Sorry if I was unclear.  I was asking @bbenligiray what needs to be fixed with the unit tests ;-)

While I definitely understand the value of shortening the inheritance chain, I'm not sure why we would want to reduce the number of contracts.  Fewer contracts means longer contracts, which I would expect to reduce the separation of concerns and make the code harder to understand / audit.

For example, it would be easy to collapse all of Api3Pool into a single file, but IMHO that would feel like a step in the wrong direction.  Part of the existing problem is that contracts like StateUtils are a mixed bag of somewhat different things, and other contracts depend on different parts of this, which is part of why the current linear inheritance chain is required.  I have started splitting components out into smaller contracts to provide cleaner abstraction boundaries, but I don't want to continue too much further with this if there's not consensus that it's the right thing to do ;-)  Let me know what you think!

**Comment by bbenligiray** [comment]
The current contract structure is my own. It's one monolithic contract that's split into files according to functionality to improve readability. Inheritance is only used to split the contract into pieces (so I wouldn't think about this as inheritance at all, just a workaround to split a monolithic contract into files). I think not having a modular architecture for this is okay because it's easy to see it as a whole, but maybe I'm too familiar with it (and also most things are pretty tightly coupled together).

I agree that having more files is better (which is why this is the way it is right now). They think that 2-3 files would be better (more readable). That's pretty subjective.

The chain can be implemented as a much shallower tree, yet I don't see that changing anything regarding readability or anything else. It would be the more proper way of doing it though.

**Comment by aspiers** [comment]
[**@bbenligiray**](https://github.com/bbenligiray) commented on [April 3, 2021 6:57 PM](https://github.com/api3dao/api3-dao/issues/150#issuecomment-812901748 "2021-04-03T17:57:53Z - Replied by Github Reply Comments"):
> The current contract structure is my own. It's one monolithic contract that's split into files according to functionality to improve readability. Inheritance is only used to split the contract into pieces (so I wouldn't think about this as inheritance at all, just a workaround to split a monolithic contract into files).

Agreed - Solidity doesn't support real mixins, so this technique using multiple inheritance is probably the easiest thing we can do to get close to that.  There are libraries, but they don't make things easy either, even though [it *is* technically possible to have state variables in libraries](https://dev.to/mudgen/solidity-libraries-can-t-have-state-variables-oh-yes-they-can-3ke9).

> I think not having a modular architecture for this is okay because it's easy to see it as a whole, but maybe I'm too familiar with it (and also most things are pretty tightly coupled together).

I already spotted one or two ways things could be decoupled.  I'll try to submit PRs for those shortly.  Maybe it's possible to decouple further, however I'm not sure about that yet.

> I agree that having more files is better (which is why this is the way it is right now). They think that 2-3 files would be better (more readable). That's pretty subjective.

Ah, that's strange.  Who is "they" in this context?

> The chain can be implemented as a much shallower tree, yet I don't see that changing anything regarding readability or anything else.

It might help clarify the dependencies between the different chunks of code, which IMHO would be a win, even if not a massive one.

> It would be the more proper way of doing it though.

Agreed, that too ;-)

This is one of the things I have managed to slightly improve, by getting rid of the huge constructor chain.  I'll submit PRs soon, hopefully later today or earlier tomorrow!

**Comment by kinspotting** [comment]
> Ah, that's strange. Who is "they" in this context?

`They` stands for Curve Labs in this context ;)

**Comment by aspiers** [comment]
OK thanks, I'll talk to Curve Labs about this then :-)

**Comment by aspiers** [comment]
@kinspotting wrote:
> limit the inheritance chain to maximum 3 contracts.

@kinspotting Reading between the lines, I'm guessing that here you meant a maximum *depth* of 3 contracts in the inheritance tree, rather than 3 contracts in total - did I understand correctly?

**Comment by aspiers** [comment]
BTW #159 is a suggested first step.  I have other changes in the works.

**Comment by kinspotting** [comment]
The issue is partially implemented, closing before the audit report results, will reopen if auditors recommend more fixes
